import express from 'express';
import path from 'path';
import { fileURLToPath } from 'url';
const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);
import cors from 'cors';
import { ApolloServer } from '@apollo/server';
import { expressMiddleware } from '@as-integrations/express4';
import { gql } from 'graphql-tag';

const teams = [
  {
    id: '1',
    name: 'Alajärven Ankkurit',
    image: '/images/alajarvi.png',
    description:
      'Alajärven Ankkurit on perustettu 26. marraskuuta 1944 ja toimii Alajärvellä, Etelä-Pohjanmaalla. Alajärven Ankkurit on yleisseura, jonka lajeja ovat pesäpallon lisäksi mm. hiihto, lentopallo ja yleisurheilu. Pesäpallo on vuosien myötä muodostunut Ankkureiden suurimmaksi ja tunnetuimmaksi lajiksi. Ankkurien kotikenttänä toimii Kitron pesäpallostadion, jonka kapasiteetti on 4000. Sen yleisöennätys 6822 katsojaa syntyi Itä-Länsi ottelussa vuonna 1995. Joukkueen peliasun päävärit ovat keltainen ja sininen.',
    achievements:
      'Ankkurit on pelannut pitkään miesten Superpesiksessä, pesäpallon korkeimmalla sarjatasolla. Alajärven Ankkureiden menestyksekkäin ajanjakso oli 1980-luku, jolloin seura saavutti yhteensä kuusi SM-mitalia. Seura on voittanut miesten pesäpallon suomenmestaruuden kaksi kertaa vuosina 1988–1989. Lisäksi Ankkurit on saavuttanut hopeaa kaksi kertaa (1980 ja 1987) ja pronssia kolme kertaa (1984, 1985 ja 1992).',
    arena: 'Kitro',
    arena_image: '/images/kitro.JPG',
    players: [
      {
        id: '1-1',
        image: '/images/placeholder.png',
        player_name: 'Miika Etula',
        player_role_in: 'Kotiuttaja',
        player_role_out: 'Koppari',
        player_info: 'https://www.pesistulokset.fi/pelaaja/14185',
      },
      {
        id: '1-2',
        image: '/images/placeholder.png',
        player_name: 'Markus Hallasuo',
        player_role_in: 'Kotiuttaja',
        player_role_out: 'Jokeri',
        player_info: 'https://www.pesistulokset.fi/pelaaja/7280',
      },
      {
        id: '1-3',
        image: '/images/placeholder.png',
        player_name: 'Eeli Hänninen',
        player_role_in: 'Vaihtaja',
        player_role_out: 'Linjapelaaja',
        player_info: 'https://www.pesistulokset.fi/pelaaja/14187',
      },
      {
        id: '1-4',
        image: '/images/placeholder.png',
        player_name: 'Elmeri Koivusalmi',
        player_role_in: 'Vaihtaja',
        player_role_out: 'Pesävahti',
        player_info: 'https://www.pesistulokset.fi/pelaaja/11144',
      },
      {
        id: '1-5',
        image: '/images/placeholder.png',
        player_name: 'Atte Kuosmanen',
        player_role_in: 'Etenijä',
        player_role_out: 'Pesävahti',
        player_info: 'https://www.pesistulokset.fi/pelaaja/9467',
      },
      {
        id: '1-6',
        image: '/images/placeholder.png',
        player_name: 'Kimi Lassila',
        player_role_in: 'Etenijä',
        player_role_out: 'Pesävahti',
        player_info: 'https://www.pesistulokset.fi/pelaaja/10436',
      },
      {
        id: '1-7',
        image: '/images/placeholder.png',
        player_name: 'Matias Litmanen',
        player_role_in: 'Vaihtaja',
        player_role_out: 'Pesävahti',
        player_info: 'https://www.pesistulokset.fi/pelaaja/7878',
      },
      {
        id: '1-8',
        image: '/images/placeholder.png',
        player_name: 'Toni Marjamäki',
        player_role_in: 'Etenijä',
        player_role_out: 'Pesävahti',
        player_info: 'https://www.pesistulokset.fi/pelaaja/5814',
      },
      {
        id: '1-9',
        image: '/images/placeholder.png',
        player_name: 'Mico Paalanen',
        player_role_in: 'Vaihtaja',
        player_role_out: 'Pesävahti',
        player_info: 'https://www.pesistulokset.fi/pelaaja/11943',
      },
      {
        id: '1-10',
        image: '/images/placeholder.png',
        player_name: 'Joona Peltokangas',
        player_role_in: 'Etenijä',
        player_role_out: 'Koppari',
        player_info: 'https://www.pesistulokset.fi/pelaaja/9825',
      },
      {
        id: '1-11',
        image: '/images/placeholder.png',
        player_name: 'Antton Peltomäki',
        player_role_in: 'Etenijä',
        player_role_out: 'Pesävahti',
        player_info: 'https://www.pesistulokset.fi/pelaaja/9645',
      },
      {
        id: '1-12',
        image: '/images/placeholder.png',
        player_name: 'Jere Peltomäki',
        player_role_in: 'Vaihtaja',
        player_role_out: 'Pesävahti',
        player_info: 'https://www.pesistulokset.fi/pelaaja/9761',
      },
      {
        id: '1-13',
        image: '/images/placeholder.png',
        player_name: 'Mikael Penninkangas',
        player_role_in: 'Vaihtaja',
        player_role_out: 'Koppari',
        player_info: 'https://www.pesistulokset.fi/pelaaja/7794',
      },
      {
        id: '1-14',
        image: '/images/placeholder.png',
        player_name: 'Seeti Surakka',
        player_role_in: 'Vaihtaja',
        player_role_out: 'Lukkari',
        player_info: 'https://www.pesistulokset.fi/pelaaja/9254',
      },
      {
        id: '1-15',
        image: '/images/placeholder.png',
        player_name: 'Niko Tuikka',
        player_role_in: 'Vaihtaja',
        player_role_out: 'Pesävahti',
        player_info: 'https://www.pesistulokset.fi/pelaaja/9201',
      },
      {
        id: '1-16',
        image: '/images/placeholder.png',
        player_name: 'Nestori Yli-Sissala',
        player_role_in: 'Vaihtaja',
        player_role_out: 'Linjapelaaja',
        player_info: 'https://www.pesistulokset.fi/pelaaja/7789',
      },
      {
        id: '1-17',
        image: '/images/placeholder.png',
        player_name: 'Samu Mattila',
        player_role_in: 'Etenijä',
        player_role_out: 'Pesävahti',
        player_info: 'https://www.pesistulokset.fi/pelaaja/14186',
      },
    ],
    coaches: [
      {
        id: '1-1',
        image: '/images/placeholder.png',
        coach_name: 'Eemil Peltomäki',
        coach_role: '1. Pelinjohtaja',
      },
      {
        id: '1-2',
        image: '/images/placeholder.png',
        coach_name: 'Mikko Vainionpää',
        coach_role: '2. Pelinjohtaja',
      },
    ],
  },
  {
    id: '2',
    name: 'Hyvinkään Tahko',
    image: '/images/hyvinkaan_tahko.png',
    description:
      'Hyvinkään Tahko on on perustettu Aseman koululla 26. toukokuuta 1915 ja toimii Hyvinkäällä, Uudellamaalla. Seura on ottanut nimensä pesäpallon kehittäjän, professori Lauri "Tahko" Pihkalan mukaan. Hyvinkään Tahko on pesäpallon erikoisseura ja miesten sekä naisten joukkueet pelaavat Superpesistä. Tahkon kotikenttänä toimii Pihkalan pesäpallostadion. Sen yleisöennätys syntyi 1992 ensimmäisessä SM-finaalissa Sotkamoa vastaan, jolloin ottelua oli katsomassa 7640 katsojaa. Joukkueen peliasun pääväri on keltainen.',
    achievements:
      'Seura on voittanut miesten pesäpallon suomenmestaruuden neljä kertaa vuosina 1979–1981, sekä 2007. Lisäksi Tahko on saavuttanut hopeaa viisi kertaa (1983, 1992, 1994, 1996 ja 1999) ja pronssia myös viisi kertaa (1978, 1982, 1989, 1990 ja 2002).',
    arena: 'Pihkala',
    arena_image: '/images/pihkala.jpg',
    players: [
      {
        id: '2-1',
        image: '/images/placeholder.png',
        player_name: 'Petteri Alanen',
        player_role_in: 'Vaihtaja',
        player_role_out: 'Lukkari',
        player_info: 'https://www.pesistulokset.fi/pelaaja/9724',
      },
      {
        id: '2-2',
        image: '/images/placeholder.png',
        player_name: 'Luka Raesmaa',
        player_role_in: 'Etenijä',
        player_role_out: 'Koppari',
        player_info: 'https://www.pesistulokset.fi/pelaaja/9571',
      },
      {
        id: '2-3',
        image: '/images/placeholder.png',
        player_name: 'Teemu Nurmio',
        player_role_in: 'Etenijä',
        player_role_out: 'Koppari',
        player_info: 'https://www.pesistulokset.fi/pelaaja/7232',
      },
      {
        id: '2-4',
        image: '/images/placeholder.png',
        player_name: 'Santtu Patova',
        player_role_in: 'Kotiuttaja',
        player_role_out: 'Linjapelaaja',
        player_info: 'https://www.pesistulokset.fi/pelaaja/7911',
      },
      {
        id: '2-5',
        image: '/images/placeholder.png',
        player_name: 'Juha Niemi',
        player_role_in: 'Kotiuttaja',
        player_role_out: 'Jokeri',
        player_info: 'https://www.pesistulokset.fi/pelaaja/4294',
      },
      {
        id: '2-6',
        image: '/images/placeholder.png',
        player_name: 'Samu Kyhyräinen',
        player_role_in: 'Vaihtaja',
        player_role_out: 'Sieppari',
        player_info: 'https://www.pesistulokset.fi/pelaaja/12934',
      },
      {
        id: '2-7',
        image: '/images/placeholder.png',
        player_name: 'Veeti Kettunen',
        player_role_in: 'Vaihtaja',
        player_role_out: 'Linjapelaaja',
        player_info: 'https://www.pesistulokset.fi/pelaaja/10446',
      },
      {
        id: '2-8',
        image: '/images/placeholder.png',
        player_name: 'Miitri Pesonen',
        player_role_in: 'Vaihtaja',
        player_role_out: 'Pesävahti',
        player_info: 'https://www.pesistulokset.fi/pelaaja/11542',
      },
      {
        id: '2-9',
        image: '/images/placeholder.png',
        player_name: 'Eero Kuitunen',
        player_role_in: 'Etenijä',
        player_role_out: 'Pesävahti',
        player_info: 'https://www.pesistulokset.fi/pelaaja/8111',
      },
      {
        id: '2-10',
        image: '/images/placeholder.png',
        player_name: 'Valentin Ikonen',
        player_role_in: 'Vaihtaja',
        player_role_out: 'Pesävahti',
        player_info: 'https://www.pesistulokset.fi/pelaaja/7004',
      },
      {
        id: '2-11',
        image: '/images/placeholder.png',
        player_name: 'Oula Tanttu',
        player_role_in: 'Vaihtaja',
        player_role_out: 'Sieppari',
        player_info: 'https://www.pesistulokset.fi/pelaaja/12451',
      },
      {
        id: '2-12',
        image: '/images/placeholder.png',
        player_name: 'Tuomas Kosonen',
        player_role_in: 'Vaihtaja',
        player_role_out: 'Pesävahti',
        player_info: 'https://www.pesistulokset.fi/pelaaja/12387',
      },
      {
        id: '2-13',
        image: '/images/placeholder.png',
        player_name: 'Paavo Lehto',
        player_role_in: 'Vaihtaja',
        player_role_out: 'Pesävahti',
        player_info: 'https://www.pesistulokset.fi/pelaaja/14058',
      },
      {
        id: '2-14',
        image: '/images/placeholder.png',
        player_name: 'Teemu Rouhiainen',
        player_role_in: 'Etenijä',
        player_role_out: 'Koppari',
        player_info: 'https://www.pesistulokset.fi/pelaaja/10898',
      },
      {
        id: '2-15',
        image: '/images/placeholder.png',
        player_name: 'Aapo Kinnunen',
        player_role_in: 'Vaihtaja',
        player_role_out: 'Pesävahti',
        player_info: 'https://www.pesistulokset.fi/pelaaja/10913',
      },
      {
        id: '2-16',
        image: '/images/placeholder.png',
        player_name: 'Aaron Honkanen',
        player_role_in: 'Etenijä',
        player_role_out: 'Lukkari',
        player_info: 'https://www.pesistulokset.fi/pelaaja/10434',
      },
      {
        id: '2-17',
        image: '/images/placeholder.png',
        player_name: 'Antti Kortteenperä',
        player_role_in: 'Vaihtaja',
        player_role_out: 'Pesävahti',
        player_info: 'https://www.pesistulokset.fi/pelaaja/8612',
      },
    ],
    coaches: [
      {
        id: '2-1',
        image: '/images/placeholder.png',
        coach_name: 'Eero Pitkänen',
        coach_role: '1. Pelinjohtaja',
      },
      {
        id: '2-2',
        image: '/images/placeholder.png',
        coach_name: 'Juha Korhonen',
        coach_role: '2. Pelinjohtaja',
      },
    ],
  },
  {
    id: '3',
    name: 'Imatran Pallo-Veikot',
    image: '/images/logo.svg',
    description:
      'Imatran Pallo-Veikot (IPV) on perustettu vuonna 1955 perustettu ja toimii Imatralla, Etelä-Karjalassa. IPV harjoittelee ja pelaa kotiottelunsa Ukonniemen stadionilla. Aiemmin kotikenttänä toimi ensin Taininkosken Maneesi ja tämän jälkeen Linnalan kenttä. Joukkueen peliasun päävärit ovat punainen ja valkoinen.',
    achievements:
      'Seura on voittanut miesten pesäpallon suomenmestaruuden neljä kertaa vuosina 1977, 1978, 1986 ja 1991. Lisäksi IPV on saavuttanut hopeaa kolme kertaa (1989, 1990 ja 1993) ja pronssia kerran (1973).',
    arena: 'Ukonniemi (kuvituskuva)',
    arena_image: '/images/stadion.jpg',
    players: [
      {
        id: '3-1',
        image: '/images/placeholder.png',
        player_name: 'Eetu Beloff',
        player_role_in: 'Vaihtaja',
        player_role_out: 'Koppari',
        player_info: 'https://www.pesistulokset.fi/pelaaja/10771',
      },
      {
        id: '3-2',
        image: '/images/placeholder.png',
        player_name: 'Valtteri Havukainen',
        player_role_in: 'Etenijä',
        player_role_out: 'Linjapelaaja',
        player_info: 'https://www.pesistulokset.fi/pelaaja/9083',
      },
      {
        id: '3-3',
        image: '/images/placeholder.png',
        player_name: 'Konsta Hyötyläinen',
        player_role_in: 'Vaihtaja',
        player_role_out: 'Linjapelaaja',
        player_info: 'https://www.pesistulokset.fi/pelaaja/7259',
      },
      {
        id: '3-4',
        image: '/images/placeholder.png',
        player_name: 'Toomas Häkkinen',
        player_role_in: 'Vaihtaja',
        player_role_out: 'Linjapelaaja',
        player_info: 'https://www.pesistulokset.fi/pelaaja/12238',
      },
      {
        id: '3-5',
        image: '/images/placeholder.png',
        player_name: 'Matias Kauppinen',
        player_role_in: 'Vaihtaja',
        player_role_out: 'Sieppari',
        player_info: 'https://www.pesistulokset.fi/pelaaja/8384',
      },
      {
        id: '3-6',
        image: '/images/placeholder.png',
        player_name: 'Mikko Kosonen',
        player_role_in: 'Vaihtaja',
        player_role_out: 'Peävahti',
        player_info: 'https://www.pesistulokset.fi/pelaaja/7701',
      },
      {
        id: '3-7',
        image: '/images/placeholder.png',
        player_name: 'Justus Niemeläinen',
        player_role_in: 'Etenijä',
        player_role_out: 'Koppari',
        player_info: 'https://www.pesistulokset.fi/pelaaja/9377',
      },
      {
        id: '3-8',
        image: '/images/placeholder.png',
        player_name: 'Ville-Veikko Olli',
        player_role_in: 'Kotiuttaja',
        player_role_out: 'Jokeri',
        player_info: 'https://www.pesistulokset.fi/pelaaja/7533',
      },
      {
        id: '3-9',
        image: '/images/placeholder.png',
        player_name: 'Arttu Parviainen',
        player_role_in: 'Etenijä',
        player_role_out: 'Pesävahti',
        player_info: 'https://www.pesistulokset.fi/pelaaja/11680',
      },
      {
        id: '3-10',
        image: '/images/placeholder.png',
        player_name: 'Rasmus Seppänen',
        player_role_in: 'Kotiuttaja',
        player_role_out: 'Lukkari',
        player_info: 'https://www.pesistulokset.fi/pelaaja/13387',
      },
      {
        id: '3-11',
        image: '/images/placeholder.png',
        player_name: 'Pietu Vesterinen',
        player_role_in: 'Vaihtaja',
        player_role_out: 'Lukkari',
        player_info: 'https://www.pesistulokset.fi/pelaaja/10334',
      },
      {
        id: '3-12',
        image: '/images/placeholder.png',
        player_name: 'Leo Gardemaister',
        player_role_in: 'Etenijä',
        player_role_out: 'Jokeri',
        player_info: 'https://www.pesistulokset.fi/pelaaja/9468',
      },
      {
        id: '3-13',
        image: '/images/placeholder.png',
        player_name: 'Ari Lankinen',
        player_role_in: 'Vaihtaja',
        player_role_out: 'Koppari',
        player_info: 'https://www.pesistulokset.fi/pelaaja/8274',
      },
      {
        id: '3-14',
        image: '/images/placeholder.png',
        player_name: 'Santeri Pasi',
        player_role_in: 'Vaihtaja',
        player_role_out: 'Pesävahti',
        player_info: 'https://www.pesistulokset.fi/pelaaja/11713',
      },
      {
        id: '3-15',
        image: '/images/placeholder.png',
        player_name: 'Aappo Savikoski',
        player_role_in: 'Vaihtaja',
        player_role_out: 'Pesävahti',
        player_info: 'https://www.pesistulokset.fi/pelaaja/9387',
      },
      {
        id: '3-16',
        image: '/images/placeholder.png',
        player_name: 'Roope Seppänen',
        player_role_in: 'Vaihtaja',
        player_role_out: 'Linjapelaaja',
        player_info: 'https://www.pesistulokset.fi/pelaaja/10355',
      },
      {
        id: '3-17',
        image: '/images/placeholder.png',
        player_name: 'Kasperi Vehkaoja',
        player_role_in: 'Vaihtaja',
        player_role_out: 'Pesävahti',
        player_info: 'https://www.pesistulokset.fi/pelaaja/10468',
      },
      {
        id: '3-18',
        image: '/images/placeholder.png',
        player_name: 'Vertti Veittikoski',
        player_role_in: 'Vaihtaja',
        player_role_out: 'Pesävahti',
        player_info: 'https://www.pesistulokset.fi/pelaaja/10950',
      },
    ],
    coaches: [
      {
        id: '3-1',
        image: '/images/placeholder.png',
        coach_name: 'Atte Hakala',
        coach_role: '1. Pelinjohtaja',
      },
      {
        id: '3-2',
        image: '/images/placeholder.png',
        coach_name: 'Saku Havukainen',
        coach_role: '2. Pelinjohtaja',
      },
    ],
  },
  {
    id: '4',
    name: 'Joensuun Maila',
    image: '/images/joensuun_maila.png',
    description:
      'Joensuun Maila (JoMa) on perustettu vuonna 1958 ja toimii Joensuussa, Pohjois-Karjalassa. Joukkueen kotikenttänä toimii Kerubi Stadion, joka sijaitsee Joensuun Mehtimäellä. Talvella harjoitus- ja pelikenttänä toimii Joensuu Areena. Joukkueen peliasun päävärit ovat punainen, valkoinen ja musta.',
    achievements:
      'Joensuun Mailan miesten pesäpallojoukkue on saavuttanut kultaa vuosina 2018 ja 2019. Lisäksi Maila on saavuttanut pronssia kuusi kertaa (2013, 2014, 2015, 2016, 2017 ja 2022).',
    arena: 'Ilosaari Rock Stadion',
    arena_image: '/images/ilosaarirock_stadion.jpg',
    players: [
      {
        id: '4-1',
        image: '/images/placeholder.png',
        player_name: 'Kasperi Hämäläinen',
        player_role_in: 'Etenijä',
        player_role_out: 'Koppari',
        player_info: 'https://www.pesistulokset.fi/pelaaja/9568',
      },
      {
        id: '4-2',
        image: '/images/placeholder.png',
        player_name: 'Onni Hirvonen',
        player_role_in: 'Vaihtaja',
        player_role_out: 'Pesävahti',
        player_info: 'https://www.pesistulokset.fi/pelaaja/16423',
      },
      {
        id: '4-3',
        image: '/images/placeholder.png',
        player_name: 'Ville Kotro',
        player_role_in: 'Vaihtaja',
        player_role_out: 'Pesävahti',
        player_info: 'https://www.pesistulokset.fi/pelaaja/7013',
      },
      {
        id: '4-4',
        image: '/images/placeholder.png',
        player_name: 'Konsta Kettunen',
        player_role_in: 'Etenijä',
        player_role_out: 'Pesävahti',
        player_info: 'https://www.pesistulokset.fi/pelaaja/8416',
      },
      {
        id: '4-5',
        image: '/images/placeholder.png',
        player_name: 'Niko Korhonen',
        player_role_in: 'Vaihtaja',
        player_role_out: 'Pesävahti',
        player_info: 'https://www.pesistulokset.fi/pelaaja/11974',
      },
      {
        id: '4-6',
        image: '/images/placeholder.png',
        player_name: 'Joni Lehikoinen',
        player_role_in: 'Vaihtaja',
        player_role_out: 'Pesävahti',
        player_info: 'https://www.pesistulokset.fi/pelaaja/8286',
      },
      {
        id: '4-7',
        image: '/images/placeholder.png',
        player_name: 'Iiro Kuosa',
        player_role_in: 'Vaihtaja',
        player_role_out: 'Pesävahti',
        player_info: 'https://www.pesistulokset.fi/pelaaja/5507',
      },
      {
        id: '4-8',
        image: '/images/placeholder.png',
        player_name: 'Veeti Lankinen',
        player_role_in: 'Vaihtaja',
        player_role_out: 'Koppari',
        player_info: 'https://www.pesistulokset.fi/pelaaja/9393',
      },
      {
        id: '4-9',
        image: '/images/placeholder.png',
        player_name: 'Joosua Rättö',
        player_role_in: 'Kotiuttaja',
        player_role_out: 'Jokeri',
        player_info: 'https://www.pesistulokset.fi/pelaaja/20452',
      },
      {
        id: '4-10',
        image: '/images/placeholder.png',
        player_name: 'Elmeri Lonkainen',
        player_role_in: 'Vaihtaja',
        player_role_out: 'Pesävahti',
        player_info: 'https://www.pesistulokset.fi/pelaaja/11172',
      },
      {
        id: '4-11',
        image: '/images/placeholder.png',
        player_name: 'Konsta Piironen',
        player_role_in: 'Vaihtaja',
        player_role_out: 'Koppari',
        player_info: 'https://www.pesistulokset.fi/pelaaja/7723',
      },
      {
        id: '4-12',
        image: '/images/placeholder.png',
        player_name: 'Ukko Schroderus',
        player_role_in: 'Vaihtaja',
        player_role_out: 'Lukkari',
        player_info: 'https://www.pesistulokset.fi/pelaaja/11421',
      },
      {
        id: '4-13',
        image: '/images/placeholder.png',
        player_name: 'Juha Toivola',
        player_role_in: 'Kotiuttaja',
        player_role_out: 'Jokeri',
        player_info: 'https://www.pesistulokset.fi/pelaaja/4607',
      },
      {
        id: '4-14',
        image: '/images/placeholder.png',
        player_name: 'Samuel Tirkkonen',
        player_role_in: 'Vaihtaja',
        player_role_out: 'Sieppari',
        player_info: 'https://www.pesistulokset.fi/pelaaja/9532',
      },
      {
        id: '4-15',
        image: '/images/placeholder.png',
        player_name: 'Mikael Virkkala',
        player_role_in: 'Vaihtaja',
        player_role_out: 'Sieppari',
        player_info: 'https://www.pesistulokset.fi/pelaaja/11179',
      },
      {
        id: '4-16',
        image: '/images/placeholder.png',
        player_name: 'Miro Kähkönen',
        player_role_in: 'Vaihtaja',
        player_role_out: 'Pesävahti',
        player_info: 'https://www.pesistulokset.fi/pelaaja/8640',
      },
      {
        id: '4-17',
        image: '/images/placeholder.png',
        player_name: 'Akseli Mäkinen',
        player_role_in: 'Vaihtaja',
        player_role_out: 'Linjapelaaja',
        player_info: 'https://www.pesistulokset.fi/pelaaja/19000',
      },
      {
        id: '4-18',
        image: '/images/placeholder.png',
        player_name: 'Aatu Mehtätalo',
        player_role_in: 'Vaihtaja',
        player_role_out: 'Pesävahti',
        player_info: 'https://www.pesistulokset.fi/pelaaja/16385',
      },
      {
        id: '4-19',
        image: '/images/placeholder.png',
        player_name: 'Kalle Antikainen',
        player_role_in: 'Etenijä',
        player_role_out: 'Koppari',
        player_info: 'https://www.pesistulokset.fi/pelaaja/11641',
      },
      {
        id: '4-20',
        image: '/images/placeholder.png',
        player_name: 'Tomi Liuski',
        player_role_in: 'Vaihtaja',
        player_role_out: 'Lukkari',
        player_info: 'https://www.pesistulokset.fi/pelaaja/11174',
      },
      {
        id: '4-21',
        image: '/images/placeholder.png',
        player_name: 'Aapo Mononen',
        player_role_in: 'Vaihtaja',
        player_role_out: 'Pesävahti',
        player_info: 'https://www.pesistulokset.fi/pelaaja/16103',
      },
    ],
    coaches: [
      {
        id: '4-1',
        image: '/images/placeholder.png',
        coach_name: 'Markus Wirzenius',
        coach_role: '1. Pelinjohtaja',
      },
      {
        id: '4-2',
        image: '/images/placeholder.png',
        coach_name: 'Joonas Hänninen',
        coach_role: '2. Pelinjohtaja',
      },
    ],
  },
  {
    id: '5',
    name: 'Kempeleen Kiri',
    image: '/images/kempeleen_kiri.png',
    description:
      'Kempeleen Kiri on perustettu vuonna 1915 ja toimii Kempeleessä, Pohjois-Pohjanmaalla. Kempeleen Kiri on urheilun yleisseura, jonka lajeja ovat pesäpallo, yleisurheilu, salibandy ja maastohiihto. Kotiottelunsa seura pelaa Sarkkirannan pesäpallostadionilla. Kentän erityispiirre on hiekkatekonurmi, joka on väriltään sininen. Kenttä myös tunnetaan nimellä "Laguuni". Kentän yleisöennätys syntyi vuonna 2015 ottelussa Oulun Lippoa vastaan, jota oli katsomassa 2 702 katsojaa. Joukkueen peliasun päävärit ovat sininen ja musta.',
    achievements:
      'Vuonna 2015 Kempeleen Kirin miesten joukkue nousi Superpesikseen. Seura on voittanut pronssia vuonna 2023',
    arena: 'Sarkkiranta (kuvituskuva)',
    arena_image: '/images/sarkkiranta_stadion.jpg',
    players: [
      {
        id: '5-1',
        image: '/images/placeholder.png',
        player_name: 'Aaro Ojanperä',
        player_role_in: 'Vaihtaja',
        player_role_out: 'Pesävahti',
        player_info: 'https://www.pesistulokset.fi/pelaaja/13781',
      },
      {
        id: '5-2',
        image: '/images/placeholder.png',
        player_name: 'Aatu Saastamoinen',
        player_role_in: 'Vaihtaja',
        player_role_out: 'Pesävahti',
        player_info: 'https://www.pesistulokset.fi/pelaaja/9143',
      },
      {
        id: '5-3',
        image: '/images/placeholder.png',
        player_name: 'Arttu Ruuska',
        player_role_in: 'Vaihtaja',
        player_role_out: 'Sieppari',
        player_info: 'https://www.pesistulokset.fi/pelaaja/283',
      },
      {
        id: '5-4',
        image: '/images/placeholder.png',
        player_name: 'Niilas Luukkonen',
        player_role_in: 'Vaihtaja',
        player_role_out: 'Pesävahti',
        player_info: 'https://www.pesistulokset.fi/pelaaja/13249',
      },
      {
        id: '5-5',
        image: '/images/placeholder.png',
        player_name: 'Joona Haapanen',
        player_role_in: 'Etenijä',
        player_role_out: 'Linjapelaaja',
        player_info: 'https://www.pesistulokset.fi/pelaaja/13244',
      },
      {
        id: '5-6',
        image: '/images/placeholder.png',
        player_name: 'Markus Keski-Petäjä',
        player_role_in: 'Vaihtaja',
        player_role_out: 'Pesävahti',
        player_info: 'https://www.pesistulokset.fi/pelaaja/7576',
      },
      {
        id: '5-7',
        image: '/images/placeholder.png',
        player_name: 'Tuukka Etula',
        player_role_in: 'Vaihtaja',
        player_role_out: 'Koppari',
        player_info: 'https://www.pesistulokset.fi/pelaaja/9081',
      },
      {
        id: '5-8',
        image: '/images/placeholder.png',
        player_name: 'Olli Heikkala',
        player_role_in: 'Vaihtaja',
        player_role_out: 'Pesävahti',
        player_info: 'https://www.pesistulokset.fi/pelaaja/12047',
      },
      {
        id: '5-9',
        image: '/images/placeholder.png',
        player_name: 'Ossi Meriläinen',
        player_role_in: 'Kotiuttja',
        player_role_out: 'Jokeri',
        player_info: 'https://www.pesistulokset.fi/pelaaja/5602',
      },
      {
        id: '5-10',
        image: '/images/placeholder.png',
        player_name: 'Paavo Hakala',
        player_role_in: 'Vaihtaja',
        player_role_out: 'Koppari',
        player_info: 'https://www.pesistulokset.fi/pelaaja/13237',
      },
      {
        id: '5-11',
        image: '/images/placeholder.png',
        player_name: 'Saku Saloranta',
        player_role_in: 'Vaihtaja',
        player_role_out: 'Linjapelaaja',
        player_info: 'https://www.pesistulokset.fi/pelaaja/13236',
      },
      {
        id: '5-12',
        image: '/images/placeholder.png',
        player_name: 'Teemu Hollanti',
        player_role_in: 'Etenijä',
        player_role_out: 'Koppari',
        player_info: 'https://www.pesistulokset.fi/pelaaja/9460',
      },
      {
        id: '5-13',
        image: '/images/placeholder.png',
        player_name: 'Tino Alaspää',
        player_role_in: 'Vaihtaja',
        player_role_out: 'Linjapelaaja',
        player_info: 'https://www.pesistulokset.fi/pelaaja/10013',
      },
      {
        id: '5-14',
        image: '/images/placeholder.png',
        player_name: 'Tuomas Jussila',
        player_role_in: 'Vaihtaja',
        player_role_out: 'Linjapelaaja',
        player_info: 'https://www.pesistulokset.fi/pelaaja/4542',
      },
      {
        id: '5-15',
        image: '/images/placeholder.png',
        player_name: 'Tuukka Sarkkinen',
        player_role_in: 'Vaihtaja',
        player_role_out: 'Linjapelaaja',
        player_info: 'https://www.pesistulokset.fi/pelaaja/8317',
      },
      {
        id: '5-16',
        image: '/images/placeholder.png',
        player_name: 'Ville Väliaho',
        player_role_in: 'Vaihtaja',
        player_role_out: 'Lukkari',
        player_info: 'https://www.pesistulokset.fi/pelaaja/7267',
      },
    ],
    coaches: [
      {
        id: '5-1',
        image: '/images/placeholder.png',
        coach_name: 'Arttu Jurvakainen',
        coach_role: '1. Pelinjohtaja',
      },
      {
        id: '5-2',
        image: '/images/placeholder.png',
        coach_name: 'Santeri Haipus',
        coach_role: '2. Pelinjohtaja',
      },
    ],
  },
  {
    id: '6',
    name: 'Kiteen-Pallo -90',
    image: '/images/kiteen_pallo.png',
    description:
      'Kiteen Pallo -90 (KiPa-90) on vuonna perustettu vuonna 1990 ja toimii Kiteessä, Pohjois-Karjalassa. KiPan kotikenttä on Kiteen Rantakenttä, joka sijaitsee Kiteenjärven rannalla. Sen yleisöennätys on 5 320, 12. syyskuuta 2000 kolmannesta ja ratkaisevasta finaalista Sotkamon Jymyä vastaan. Joukkueen peliasun päävärit ovat punainen, keltainen, valkoinen ja musta.',
    achievements:
      'Joukkue on voittanut kolme SM-kultaa (1999, 2000, 2005). Lisäksi se on saavuttanut hopeaa kolme kertaa  (1997, 2001 ja 2004) ja pronssia kerran (1998).',
    arena: 'Rantakenttä',
    arena_image: '/images/rantakentta_stadion.jpg',
    players: [
      {
        id: '6-1',
        image: '/images/placeholder.png',
        player_name: 'Topias Kaksonen',
        player_role_in: 'Vaihtaja',
        player_role_out: 'Sieppari',
        player_info: 'https://www.pesistulokset.fi/pelaaja/10387',
      },
      {
        id: '6-2',
        image: '/images/placeholder.png',
        player_name: 'Otto Kauppinen',
        player_role_in: 'Etenijä',
        player_role_out: 'Pesävahti',
        player_info: 'https://www.pesistulokset.fi/pelaaja/8518',
      },
      {
        id: '6-3',
        image: '/images/placeholder.png',
        player_name: 'Juho Keinänen',
        player_role_in: 'Vaihtaja',
        player_role_out: 'Pesävahti',
        player_info: 'https://www.pesistulokset.fi/pelaaja/7885',
      },
      {
        id: '6-4',
        image: '/images/placeholder.png',
        player_name: 'Aku Kettunen',
        player_role_in: 'Vaihtaja',
        player_role_out: 'Pesävahti',
        player_info: 'https://www.pesistulokset.fi/pelaaja/7909',
      },
      {
        id: '6-5',
        image: '/images/placeholder.png',
        player_name: 'Jonne Matikainen',
        player_role_in: 'Vaihtaja',
        player_role_out: 'Lukkari',
        player_info: 'https://www.pesistulokset.fi/pelaaja/11417',
      },
      {
        id: '6-6',
        image: '/images/placeholder.png',
        player_name: 'Janne Mäkelä',
        player_role_in: 'Kotiuttaja',
        player_role_out: 'Jokeri',
        player_info: 'https://www.pesistulokset.fi/pelaaja/3509',
      },
      {
        id: '6-7',
        image: '/images/placeholder.png',
        player_name: 'Oiva Mämmi',
        player_role_in: 'Vaihtaja',
        player_role_out: 'Lukkari',
        player_info: 'https://www.pesistulokset.fi/pelaaja/13284',
      },
      {
        id: '6-8',
        image: '/images/placeholder.png',
        player_name: 'Eeli Partanen',
        player_role_in: 'Vaihtaja',
        player_role_out: 'Linjapelaaja',
        player_info: 'https://www.pesistulokset.fi/pelaaja/13282',
      },
      {
        id: '6-9',
        image: '/images/placeholder.png',
        player_name: 'Elmo Partanen',
        player_role_in: 'Vaihtaja',
        player_role_out: 'Koppari',
        player_info: 'https://www.pesistulokset.fi/pelaaja/13283',
      },
      {
        id: '6-10',
        image: '/images/placeholder.png',
        player_name: 'Jiri Pippola',
        player_role_in: 'Kotiuttaja',
        player_role_out: 'Jokeri',
        player_info: 'https://www.pesistulokset.fi/pelaaja/11603',
      },
      {
        id: '6-11',
        image: '/images/placeholder.png',
        player_name: 'Jasperi Purmonen',
        player_role_in: 'Etenijä',
        player_role_out: 'Koppari',
        player_info: 'https://www.pesistulokset.fi/pelaaja/10547',
      },
      {
        id: '6-12',
        image: '/images/placeholder.png',
        player_name: 'Rasmus Surakka',
        player_role_in: 'Vaihtaja',
        player_role_out: 'Lukkari',
        player_info: 'https://www.pesistulokset.fi/pelaaja/11550',
      },
      {
        id: '6-13',
        image: '/images/placeholder.png',
        player_name: 'Samu-Kalle Varonen',
        player_role_in: 'Vaihtaja',
        player_role_out: 'Koppari',
        player_info: 'https://www.pesistulokset.fi/pelaaja/2254',
      },
      {
        id: '6-14',
        image: '/images/placeholder.png',
        player_name: 'Sulo-Veikko Varonen',
        player_role_in: 'Etenijä',
        player_role_out: 'Linjapelaaja',
        player_info: 'https://www.pesistulokset.fi/pelaaja/16427',
      },
      {
        id: '6-15',
        image: '/images/placeholder.png',
        player_name: 'Lassi Vasarainen',
        player_role_in: 'Vaihtaja',
        player_role_out: 'Koppari',
        player_info: 'https://www.pesistulokset.fi/pelaaja/9528',
      },
      {
        id: '6-16',
        image: '/images/placeholder.png',
        player_name: 'Anttoni Jakobsson',
        player_role_in: 'Vaihtaja',
        player_role_out: 'Pesävahti',
        player_info: 'https://www.pesistulokset.fi/pelaaja/9528',
      },
      {
        id: '6-17',
        image: '/images/placeholder.png',
        player_name: 'Kasperi Kaksonen',
        player_role_in: 'Etenijä',
        player_role_out: 'Pesävahti',
        player_info: 'https://www.pesistulokset.fi/pelaaja/9528',
      },
      {
        id: '6-18',
        image: '/images/placeholder.png',
        player_name: 'Niko Halttunen',
        player_role_in: 'Vaihtaja',
        player_role_out: 'Pesävahti',
        player_info: 'https://www.pesistulokset.fi/pelaaja/9528',
      },
      {
        id: '6-19',
        image: '/images/placeholder.png',
        player_name: 'Anssi Halttunen',
        player_role_in: 'Vaihtaja',
        player_role_out: 'Sieppari',
        player_info: 'https://www.pesistulokset.fi/pelaaja/9528',
      },
    ],
    coaches: [
      {
        id: '6-1',
        image: '/images/placeholder.png',
        coach_name: 'Sami Partanen',
        coach_role: '1. Pelinjohtaja',
      },
      {
        id: '6-2',
        image: '/images/placeholder.png',
        coach_name: 'Jussi Hurskainen',
        coach_role: '2. Pelinjohtaja',
      },
    ],
  },

  {
    id: '7',
    name: 'Koskenkorvan Urheilijat',
    image: '/images/logo.svg',
    description:
      'Koskenkorvan Urheilijat (KoU, Koskenkorva, "Kossu"), viralliselta nimeltään Koskenkorvan Urheilijat on perustettu vuonna 1945 ja toimii Ilmajoen Koskenkorvan kylässä, Etelä-Pohjanmaalla. Kotiottelunsa KoU pelaa Koskenkorvan Honkalanmäellä sijaitsevalla Sähkökoje-Areenalla, jonka yleisökapasiteetti istumapaikkojen puolesta on 2500 katsojaa. Seuran yleisöennätys on 3547 katsojaa, joka syntyi 26. elokuuta 2007 ottelussa Vimpelin Vetoa vastaan. Joukkueen peliasun päävärit ovat punainen, musta, harmaa ja valkoinen.',
    achievements:
      'Koskenkorvan Urheilijat on voittanut SM-pronssia 2003 ja 2007.',
    arena: 'Sähkökone Areena',
    arena_image: '/images/sahkokoje_areena.JPG',
    players: [
      {
        id: '7-1',
        image: '/images/placeholder.png',
        player_name: 'Joona Anttila',
        player_role_in: 'Kotiuttaja',
        player_role_out: 'Jokeri',
        player_info: 'https://www.pesistulokset.fi/pelaaja/8322',
      },
      {
        id: '7-2',
        image: '/images/placeholder.png',
        player_name: 'Tuomo Hakala',
        player_role_in: 'Vaihtaja',
        player_role_out: 'Lukkari',
        player_info: 'https://www.pesistulokset.fi/pelaaja/13661',
      },
      {
        id: '7-3',
        image: '/images/placeholder.png',
        player_name: 'Eetu Heiniluoma',
        player_role_in: 'Etenijä',
        player_role_out: 'Sieppari',
        player_info: 'https://www.pesistulokset.fi/pelaaja/11012',
      },
      {
        id: '7-4',
        image: '/images/placeholder.png',
        player_name: 'Topi Kujala',
        player_role_in: 'Vaihtaja',
        player_role_out: 'Sieppari',
        player_info: 'https://www.pesistulokset.fi/pelaaja/12398',
      },
      {
        id: '7-5',
        image: '/images/placeholder.png',
        player_name: 'Wili Laiho',
        player_role_in: 'Vaihtaja',
        player_role_out: 'Linjapelaaja',
        player_info: 'https://www.pesistulokset.fi/pelaaja/15911',
      },
      {
        id: '7-6',
        image: '/images/placeholder.png',
        player_name: 'Tony Latvala',
        player_role_in: 'Vaihtaja',
        player_role_out: 'Linjapelaaja',
        player_info: 'https://www.pesistulokset.fi/pelaaja/10497',
      },
      {
        id: '7-7',
        image: '/images/placeholder.png',
        player_name: 'Eetu Lehto',
        player_role_in: 'Vaihtaja',
        player_role_out: 'Linjapelaaja',
        player_info: 'https://www.pesistulokset.fi/pelaaja/11330',
      },
      {
        id: '7-8',
        image: '/images/placeholder.png',
        player_name: 'Miki Likander',
        player_role_in: 'Vaihtaja',
        player_role_out: 'Koppari',
        player_info: 'https://www.pesistulokset.fi/pelaaja/10919',
      },
      {
        id: '7-9',
        image: '/images/placeholder.png',
        player_name: 'Joel Lähde',
        player_role_in: '?',
        player_role_out: '?',
        player_info: 'https://www.pesistulokset.fi/pelaaja/13022',
      },
      {
        id: '7-10',
        image: '/images/placeholder.png',
        player_name: 'Miska Mäkiviita',
        player_role_in: 'Etenijä',
        player_role_out: 'Linjapelaaja',
        player_info: 'https://www.pesistulokset.fi/pelaaja/10533',
      },
      {
        id: '7-11',
        image: '/images/placeholder.png',
        player_name: 'Eero Penttilä',
        player_role_in: '?',
        player_role_out: '?',
        player_info: 'https://www.pesistulokset.fi/pelaaja/15903',
      },
      {
        id: '7-12',
        image: '/images/placeholder.png',
        player_name: 'Aleksi Rauhala',
        player_role_in: 'Vaihtaja',
        player_role_out: 'Linjapelaaja',
        player_info: 'https://www.pesistulokset.fi/pelaaja/14237',
      },
      {
        id: '7-13',
        image: '/images/placeholder.png',
        player_name: 'Matias Rauhala',
        player_role_in: 'Vaihtaja',
        player_role_out: 'Koppari',
        player_info: 'https://www.pesistulokset.fi/pelaaja/9997',
      },
      {
        id: '7-14',
        image: '/images/placeholder.png',
        player_name: 'Joonas Riihimäki',
        player_role_in: 'Jokeri',
        player_role_out: '?',
        player_info: 'https://www.pesistulokset.fi/pelaaja/8611',
      },
      {
        id: '7-15',
        image: '/images/placeholder.png',
        player_name: 'Jerry Saarinen',
        player_role_in: 'Vaihtaja',
        player_info: 'https://www.pesistulokset.fi/pelaaja/14823',
        player_role_out: 'Lukkari',
      },
      {
        id: '7-16',
        image: '/images/placeholder.png',
        player_name: 'Santeri Salmela',
        player_role_in: 'Vaihtaja',
        player_role_out: 'Lukkari',
        player_info: 'https://www.pesistulokset.fi/pelaaja/11434',
      },
      {
        id: '7-17',
        image: '/images/placeholder.png',
        player_name: 'Aapeli Suvisalmi',
        player_role_in: 'Vaihtaja',
        player_role_out: 'Pesävahti',
        player_info: 'https://www.pesistulokset.fi/pelaaja/8688',
      },
      {
        id: '7-18',
        image: '/images/placeholder.png',
        player_name: 'Justus Teppo',
        player_role_in: 'Jokeri',
        player_role_out: 'Sieppari',
        player_info: 'https://www.pesistulokset.fi/pelaaja/10153',
      },
      {
        id: '7-19',
        image: '/images/placeholder.png',
        player_name: 'Luukas Teppo',
        player_role_in: 'Vaihtaja',
        player_role_out: 'Pesävahti',
        player_info: 'https://www.pesistulokset.fi/pelaaja/12527',
      },
      {
        id: '7-20',
        image: '/images/placeholder.png',
        player_name: 'Rasmus Teppo',
        player_role_in: 'Kotiuttaja',
        player_role_out: 'Jokeri',
        player_info: 'https://www.pesistulokset.fi/pelaaja/9064',
      },
    ],
    coaches: [
      {
        id: '7-1',
        image: '/images/placeholder.png',
        coach_name: 'Santeri Särkinen',
        coach_role: '1. Pelinjohtaja',
      },
      {
        id: '7-2',
        image: '/images/placeholder.png',
        coach_name: 'Janne Rauhala',
        coach_role: '2. Pelinjohtaja',
      },
    ],
  },
  {
    id: '8',
    name: 'Kouvolan Pallonlyöjät',
    image: '/images/logo.svg',
    description:
      'Kouvolan Pallonlyöjät on perustettu 2. lokakuuta vuonna 1931 ja toimii Kouvolassa, Kymenlaaksossa. Kouvolan Pallonlyöjät on pesäpallon erikoisseura. Joukkueen nimestä käytetään lyhennystä KPL ja kutsumanimeä Kopla. Joukkueen kotikenttä on Kouvolan urheilupuistossa sijaitseva KSS Energia Areena. Areenan yleisöennätys on 5648 katsojaa ja se syntyi miesten Superpesiksen kolmannessa finaaliottelussa Kouvola-Vimpeli 11.9.2010. Seuran tunnusvärit ovat musta ja keltainen.',
    achievements:
      'Kouvolan Pallonlyöjien miesten pesäpallojoukkue on saavuttanut kultaa vuosina  1966, 1967, 1968, 1969 ja 1976. Lisäksi se on saavuttanut hopeaa yhdeksän kertaa (1943, 1955, 1960, 1970, 2009, 2010, 2018, 2020 ja 2021) ja pronssia seitsemän kertaa (1954, 1959, 1972, 1977, 2019, 2024 ja 2025).',
    arena: 'KSS Energia Areena',
    arena_image: '/images/kss_energia_areena.jpg',
    players: [
      {
        id: '8-1',
        image: '/images/placeholder.png',
        player_name: 'Jesse Eskelinen',
        player_role_in: 'Etenijä',
        player_role_out: 'Linjapelaaja',
        player_info: 'https://www.pesistulokset.fi/pelaaja/2900',
      },
      {
        id: '8-2',
        image: '/images/placeholder.png',
        player_name: 'Perttu Kenttäaho',
        player_role_in: 'Etenijä',
        player_role_out: 'Koppari',
        player_info: 'https://www.pesistulokset.fi/pelaaja/10788',
      },
      {
        id: '8-3',
        image: '/images/placeholder.png',
        player_name: 'Eemeli Laine',
        player_role_in: 'Etenijä',
        player_role_out: 'Etukenttä',
        player_info: 'https://www.pesistulokset.fi/pelaaja/10346',
      },
      {
        id: '8-4',
        image: '/images/placeholder.png',
        player_name: 'Jasperi Luoma',
        player_role_in: 'Etenijä',
        player_role_out: 'Etukenttä',
        player_info: 'https://www.pesistulokset.fi/pelaaja/10912',
      },
      {
        id: '8-5',
        image: '/images/placeholder.png',
        player_name: 'Valtteri Luoma',
        player_role_in: 'Vaihtaja',
        player_role_out: 'Etukenttä',
        player_info: 'https://www.pesistulokset.fi/pelaaja/8112',
      },
      {
        id: '8-6',
        image: '/images/placeholder.png',
        player_name: 'Tommi Mäentausta',
        player_role_in: 'Etenijä',
        player_role_out: 'Koppari',
        player_info: 'https://www.pesistulokset.fi/pelaaja/5713',
      },
      {
        id: '8-7',
        image: '/images/placeholder.png',
        player_name: 'Teemu Nikkanen',
        player_role_in: 'Lyöjäjokeri',
        player_role_out: 'Jokeri',
        player_info: 'https://www.pesistulokset.fi/pelaaja/6140',
      },
      {
        id: '8-8',
        image: '/images/placeholder.png',
        player_name: 'Akseli Pitkänen',
        player_role_in: 'Vaihtaja',
        player_role_out: 'Linjapelaaja',
        player_info: 'https://www.pesistulokset.fi/pelaaja/10262',
      },
      {
        id: '8-9',
        image: '/images/placeholder.png',
        player_name: 'Elias Pitkänen',
        player_role_in: 'Vaihtaja',
        player_role_out: 'Lukkari',
        player_info: 'https://www.pesistulokset.fi/pelaaja/9939',
      },
      {
        id: '8-10',
        image: '/images/placeholder.png',
        player_name: 'Patrik Vartama',
        player_role_in: 'Etenijä',
        player_role_out: 'Linjapelaaja',
        player_info: 'https://www.pesistulokset.fi/pelaaja/8119',
      },
      {
        id: '8-11',
        image: '/images/placeholder.png',
        player_name: 'Patrik Wahlsten',
        player_role_in: 'Lyöjäjokeri',
        player_role_out: 'Jokeri',
        player_info: 'https://www.pesistulokset.fi/pelaaja/6733',
      },
      {
        id: '8-12',
        image: '/images/placeholder.png',
        player_name: 'Jali Hyttinen',
        player_role_in: 'Etenijä',
        player_role_out: 'Etukenttä',
        player_info: 'https://www.pesistulokset.fi/pelaaja/6733',
      },
      {
        id: '8-13',
        image: '/images/placeholder.png',
        player_name: 'Jiri Joukainen',
        player_role_in: 'Vaihtaja',
        player_role_out: 'Etukenttä',
        player_info: 'https://www.pesistulokset.fi/pelaaja/6733',
      },
      {
        id: '8-14',
        image: '/images/placeholder.png',
        player_name: 'Ville Pesu',
        player_role_in: 'Etenijä',
        player_role_out: 'Etukenttä',
        player_info: 'https://www.pesistulokset.fi/pelaaja/6733',
      },
      {
        id: '8-15',
        image: '/images/placeholder.png',
        player_name: 'Aleksi Haatainen',
        player_role_in: 'Vaihtaja',
        player_role_out: 'Pesävahti',
        player_info: 'https://www.pesistulokset.fi/pelaaja/6733',
      },
      {
        id: '8-16',
        image: '/images/placeholder.png',
        player_name: 'Toni Tossavainen',
        player_role_in: 'Vaihtaja',
        player_role_out: 'Koppari',
        player_info: 'https://www.pesistulokset.fi/pelaaja/6733',
      },
    ],
    coaches: [
      {
        id: '8-1',
        image: '/images/placeholder.png',
        coach_name: 'Petri Tuuva',
        coach_role: '1. Pelinjohtaja',
      },
      {
        id: '8-2',
        image: '/images/placeholder.png',
        coach_name: 'Juuso Ilander',
        coach_role: '1. Pelinjohtaja',
      },
    ],
  },
  {
    id: '9',
    name: 'Manse PP',
    image: '/images/logo.svg',
    description:
      'Manse PP on perustettu 11. huhtikuuta 2005 ja toimii Tampereella, Pirkanmaalla. Manse PP on pesäpallon erikoisseura. Manse PP pelaa kotiottelunsa Kaupin pesäpallostadionilla. Joukkueen peliasun päävärit ovat musta ja punainen. Seuralla on myös menestyvä naisjoukkue Superpesiksessä. Joukkueen peliasun päävärit ovat musta, valkoinen ja punainen.',
    achievements:
      'Manse PP nousi kaudeksi 2020 Superpesikseen. Seura on voittanut kultaa vuosina 2021 ja 2025 ja hopeaa vuonna 2022 ja 2024.',
    arena: 'Kaupin urheilustadion',
    arena_image: '/images/kauppi.jpg',
    players: [
      {
        id: '9-1',
        image: '/images/placeholder.png',
        player_name: 'Tino Heikkilä',
        player_role_in: 'Vaihtaja',
        player_role_out: 'Linjapelaaja',
        player_info: 'https://www.pesistulokset.fi/pelaaja/11350',
      },
      {
        id: '9-2',
        image: '/images/placeholder.png',
        player_name: 'Toma Heikkilä',
        player_role_in: 'Vaihtaja',
        player_role_out: 'Pesävahti',
        player_info: 'https://www.pesistulokset.fi/pelaaja/11358',
      },
      {
        id: '9-3',
        image: '/images/placeholder.png',
        player_name: 'Valtteri Hämäläinen',
        player_role_in: 'Vaihtaja',
        player_role_out: 'Koppari',
        player_info: 'https://www.pesistulokset.fi/pelaaja/7918',
      },
      {
        id: '9-4',
        image: '/images/placeholder.png',
        player_name: 'Aapo Komulainen',
        player_role_in: 'Vaihtaja',
        player_role_out: 'Lukkari',
        player_info: 'https://www.pesistulokset.fi/pelaaja/9500',
      },
      {
        id: '9-5',
        image: '/images/placeholder.png',
        player_name: 'Antti Korhonen',
        player_role_in: 'Kotiuttaja',
        player_role_out: 'Pesävahti',
        player_info: 'https://www.pesistulokset.fi/pelaaja/2941',
      },
      {
        id: '9-6',
        image: '/images/placeholder.png',
        player_name: 'Tomi Lehtonen',
        player_role_in: 'Vaihtaja',
        player_role_out: 'Sieppari',
        player_info: 'https://www.pesistulokset.fi/pelaaja/9542',
      },
      {
        id: '9-7',
        image: '/images/placeholder.png',
        player_name: 'Elmeri Lieto',
        player_role_in: 'Vaihtaja',
        player_role_out: 'Linjapelaaja',
        player_info: 'https://www.pesistulokset.fi/pelaaja/8440',
      },
      {
        id: '9-8',
        image: '/images/placeholder.png',
        player_name: 'Juuso Myllyniemi',
        player_role_in: 'Etenijä',
        player_role_out: 'Pesävahti',
        player_info: 'https://www.pesistulokset.fi/pelaaja/6090',
      },
      {
        id: '9-9',
        image: '/images/placeholder.png',
        player_name: 'Kaapo Mäkelä',
        player_role_in: 'Vaihtaja',
        player_role_out: 'Koppari',
        player_info: 'https://www.pesistulokset.fi/pelaaja/12158',
      },
      {
        id: '9-10',
        image: '/images/placeholder.png',
        player_name: 'Matias Paananen',
        player_role_in: 'Vaihtaja',
        player_role_out: 'Linjapelaaja',
        player_info: 'https://www.pesistulokset.fi/pelaaja/11014',
      },
      {
        id: '9-11',
        image: '/images/placeholder.png',
        player_name: 'Roni Rintala',
        player_role_in: 'Vaihtaja',
        player_role_out: 'Linjapelaaja',
        player_info: 'https://www.pesistulokset.fi/pelaaja/12526',
      },
      {
        id: '9-12',
        image: '/images/placeholder.png',
        player_name: 'Perttu Ruuska',
        player_role_in: 'Kotiuttaja',
        player_role_out: 'Jokeri',
        player_info: 'https://www.pesistulokset.fi/pelaaja/8574',
      },
      {
        id: '9-13',
        image: '/images/placeholder.png',
        player_name: 'Severi Tikkakoski',
        player_role_in: 'Etenijä',
        player_role_out: 'Linjapelaaja',
        player_info: 'https://www.pesistulokset.fi/pelaaja/8878',
      },
      {
        id: '9-14',
        image: '/images/placeholder.png',
        player_name: 'Simo Vainikainen',
        player_role_in: 'Vaihtaja',
        player_role_out: 'Pesävahti',
        player_info: 'https://www.pesistulokset.fi/pelaaja/6640',
      },
      {
        id: '9-15',
        image: '/images/placeholder.png',
        player_name: 'Jukka-Pekka Vainionpää',
        player_role_in: 'Kotiuttaja',
        player_role_out: 'Jokeri',
        player_info: 'https://www.pesistulokset.fi/pelaaja/4911',
      },
      {
        id: '9-16',
        image: '/images/placeholder.png',
        player_name: 'Perttu Olli',
        player_role_in: 'Etenijä',
        player_role_out: 'Koppari',
        player_info: 'https://www.pesistulokset.fi/pelaaja/9527',
      },
    ],
    coaches: [
      {
        id: '9-1',
        image: '/images/placeholder.png',
        coach_name: 'Altti-Jussi Ronkainen',
        coach_role: '1. Pelinjohtaja',
      },
      {
        id: '9-2',
        image: '/images/placeholder.png',
        coach_name: 'Saku Komulainen',
        coach_role: '2 Pelinjohtaja',
      },
    ],
  },
  {
    id: '10',
    name: 'Pattijoen Urheilijat',
    image: '/images/logo.svg',
    description:
      'Pattijoen Urheilijat eli PattU on perustettu vuonna 1928 ja toimii Raahessa, Pohjois-Pohjanmaalla. Pattijoen Urheilijoiden pesäpallotoiminta käynnistettiin uudelleen vuonna 1972. Seuran kotikenttä Miilu-areena (Rännäri) sijaitsee Pattijoella, joka liitettiin Raahen kaupunkiin vuonna 2003. Rännärin katsojaennätys on vuoden 2008 Itä-Länsi -ottelusta, jolloin katsojia oli paikalla yhteensä 4830. Pattijoen Urheilijoiden omassa kotipelissä katsojaennätys on niin ikään vuodelta 2008 neljännessä finaalissa, jolloin katsojia oli 3512. Joukkueen peliasun päävärit ovat musta ja keltainen.',
    achievements:
      'Pattijoen Urheilijoiden miesten joukkue on saavuttanut yhden Suomen mestaruuden (2008) ja kaksi hopeaa (2002 ja 2006) ja kolme pronssia (2001, 2011 ja 2012).',
    arena: 'Rännäri (kuvituskuva)',
    arena_image: '/images/stadion.jpg',
    players: [
      {
        id: '10-1',
        image: '/images/placeholder.png',
        player_name: 'Niilo Isoherranen',
        player_role_in: 'Vaihtaja',
        player_role_out: 'Linjapelaaja',
        player_info: 'https://www.pesistulokset.fi/pelaaja/12380',
      },
      {
        id: '10-2',
        image: '/images/placeholder.png',
        player_name: 'Antti Karjaluoto',
        player_role_in: 'Vaihtaja',
        player_role_out: 'Linjapelaaja',
        player_info: 'https://www.pesistulokset.fi/pelaaja/2861',
      },
      {
        id: '10-3',
        image: '/images/placeholder.png',
        player_name: 'Jaakko Kemppainen',
        player_role_in: 'Vaihtaja',
        player_role_out: 'Sieppari',
        player_info: 'https://www.pesistulokset.fi/pelaaja/7735',
      },
      {
        id: '10-4',
        image: '/images/placeholder.png',
        player_name: 'Antti Kiiskinen',
        player_role_in: 'Vaihtaja',
        player_role_out: 'Pesävahti',
        player_info: 'https://www.pesistulokset.fi/pelaaja/1444',
      },
      {
        id: '10-5',
        image: '/images/placeholder.png',
        player_name: 'Vertti Kontinaho',
        player_role_in: 'Vaihtaja',
        player_role_out: 'Koppari',
        player_info: 'https://www.pesistulokset.fi/pelaaja/10193',
      },
      {
        id: '10-6',
        image: '/images/placeholder.png',
        player_name: 'Miska Laitila',
        player_role_in: 'Vaihtaja',
        player_role_out: 'Pesävahti',
        player_info: 'https://www.pesistulokset.fi/pelaaja/16348',
      },
      {
        id: '10-7',
        image: '/images/placeholder.png',
        player_name: 'Konsta Launonen',
        player_role_in: 'Vaihtaja',
        player_role_out: 'Pesävahti',
        player_info: 'https://www.pesistulokset.fi/pelaaja/9904',
      },
      {
        id: '10-8',
        image: '/images/placeholder.png',
        player_name: 'Eemeli Mikkilä',
        player_role_in: 'Kotiuttaja',
        player_role_out: 'Jokeri',
        player_info: 'https://www.pesistulokset.fi/pelaaja/10350',
      },
      {
        id: '10-9',
        image: '/images/placeholder.png',
        player_name: 'Mikael Mäkelä',
        player_role_in: 'Etenijä',
        player_role_out: 'Pesävahti',
        player_info: 'https://www.pesistulokset.fi/pelaaja/9986',
      },
      {
        id: '10-10',
        image: '/images/placeholder.png',
        player_name: 'Onni Määttä',
        player_role_in: 'Vaihtaja',
        player_role_out: 'Pesävahti',
        player_info: 'https://www.pesistulokset.fi/pelaaja/7382',
      },
      {
        id: '10-11',
        image: '/images/placeholder.png',
        player_name: 'Marcus Nissilä',
        player_role_in: 'Vaihtaja',
        player_role_out: 'Pesävahti',
        player_info: 'https://www.pesistulokset.fi/pelaaja/13852',
      },
      {
        id: '10-12',
        image: '/images/placeholder.png',
        player_name: 'Topi Still',
        player_role_in: 'Vaihtaja',
        player_role_out: 'Lukkari',
        player_info: 'https://www.pesistulokset.fi/pelaaja/10289',
      },
      {
        id: '10-13',
        image: '/images/placeholder.png',
        player_name: 'Vili Still',
        player_role_in: 'Vaihtaja',
        player_role_out: 'Linjapelaaja',
        player_info: 'https://www.pesistulokset.fi/pelaaja/10522',
      },
      {
        id: '10-14',
        image: '/images/placeholder.png',
        player_name: 'Martti Viitasalo',
        player_role_in: 'Kotiuttaja',
        player_role_out: 'Jokeri',
        player_info: 'https://www.pesistulokset.fi/pelaaja/8952',
      },
      {
        id: '10-15',
        image: '/images/placeholder.png',
        player_name: 'Aatu Vuorinen',
        player_role_in: 'Vaihtaja',
        player_role_out: 'Pesävahti',
        player_info: 'https://www.pesistulokset.fi/pelaaja/10560',
      },
      {
        id: '10-16',
        image: '/images/placeholder.png',
        player_name: 'Oskari Lukkari',
        player_role_in: 'Etenijä',
        player_role_out: 'Koppari',
        player_info: 'https://www.pesistulokset.fi/pelaaja/8767',
      },
      {
        id: '10-17',
        image: '/images/placeholder.png',
        player_name: 'Veeti Venäläinen',
        player_role_in: 'Vaihtaja',
        player_role_out: 'Pesävahti',
        player_info: 'https://www.pesistulokset.fi/pelaaja/11622',
      },
    ],
    coaches: [
      {
        id: '10-1',
        image: '/images/placeholder.png',
        coach_name: 'Perttu Westersund',
        coach_role: '1. Pelinjohtaja',
      },
      {
        id: '10-2',
        image: '/images/placeholder.png',
        coach_name: 'Matti Leponiemi',
        coach_role: '2. Pelinjohtaja',
      },
    ],
  },

  {
    id: '11',
    name: 'Sotkamon Jymy',
    image: '/images/sotkamon_jymy.png',
    description:
      'Sotkamon Jymy on perustettu vuonna 1909 ja toimii Sotkamossa, Kainuussa. Sotkamon Jymy on sotkamolainen urheilun yleisseura. Jymy tunnetaan parhaiten pesäpallojaostostaan, joka on lajissaan Suomen kaikkien aikojen menestynein seura 18 Suomen mestaruudellaan. Sotkamon Jymy pelaa kotiottelunsa Sotkamon keskustassa, Sapsojärven rannalla sijaitsevalla Hiukan pesäpallostadionilla. Joukkueen peliasun päävärit ovat oranssi ja turkoosi.',
    achievements:
      'Sotkamon Jymy on yksi Suomen kaikkien aikojen menestyksekkäimpiä pesäpalloseuroja. Sotkamon mitalitilillä on mestaruudet vuosilta 1963, 1990, 1992, 1993, 1995, 1996, 1997, 2001, 2002, 2003, 2004, 2006, 2009, 2011, 2012, 2013, 2014, 2015, 2020, 2023 ja 2024. Hopeamitaleja on kahdeksan kappaletta vuosilta 1991, 2000, 2007, 2008, 2016, 2017, 2019 ja 2025. Pronssisia mitaleja on kolme kappaletta: 1994, 2005 ja 2010. Sotkamon Jymyllä oli vuosien 2000 ja 2017 välillä ennätyksellinen 18 mitalin mitaliputki.',
    arena: 'Hiukka',
    arena_image: '/images/hiukka.jpg',
    players: [
      {
        id: '11-1',
        image: '/images/placeholder.png',
        player_name: 'Aapo Hiltunen',
        player_role_in: 'Kotiuttaja',
        player_role_out: 'Jokeri',
        player_info: 'https://www.pesistulokset.fi/pelaaja/11969',
      },
      {
        id: '11-2',
        image: '/images/placeholder.png',
        player_name: 'Aatu Savelainen',
        player_role_in: 'Vaihtaja',
        player_role_out: 'Sieppari',
        player_info: 'https://www.pesistulokset.fi/pelaaja/12294',
      },
      {
        id: '11-3',
        image: '/images/placeholder.png',
        player_name: 'Aleksanteri Huotari',
        player_role_in: 'Vaihtaja',
        player_role_out: 'Pesävahti',
        player_info: 'https://www.pesistulokset.fi/pelaaja/9666',
      },
      {
        id: '11-4',
        image: '/images/placeholder.png',
        player_name: 'Ari Lankinen',
        player_role_in: 'Vaihtaja',
        player_role_out: 'Koppari',
        player_info: 'https://www.pesistulokset.fi/pelaaja/8274',
      },
      {
        id: '11-5',
        image: '/images/placeholder.png',
        player_name: 'Artturi Niskala',
        player_role_in: 'Vaihtaja',
        player_role_out: 'Pesävahti',
        player_info: 'https://www.pesistulokset.fi/pelaaja/12049',
      },
      {
        id: '11-6',
        image: '/images/placeholder.png',
        player_name: 'Atte Pelkonen',
        player_role_in: 'Etenijä',
        player_role_out: 'Koppari',
        player_info: 'https://www.pesistulokset.fi/pelaaja/10777',
      },
      {
        id: '11-7',
        image: '/images/placeholder.png',
        player_name: 'Elmeri Iivonen',
        player_role_in: 'Vaihtaja',
        player_role_out: 'Lukkari',
        player_info: 'https://www.pesistulokset.fi/pelaaja/12933',
      },
      {
        id: '11-8',
        image: '/images/placeholder.png',
        player_name: 'Elmeri Purmonen',
        player_role_in: 'Etenijä',
        player_role_out: 'Jokeri',
        player_info: 'https://www.pesistulokset.fi/pelaaja/9471',
      },
      {
        id: '11-9',
        image: '/images/placeholder.png',
        player_name: 'Iivari Vihanto',
        player_role_in: 'Etenijä',
        player_role_out: 'Koppari',
        player_info: 'https://www.pesistulokset.fi/pelaaja/9971',
      },
      {
        id: '11-10',
        image: '/images/placeholder.png',
        player_name: 'Hannes Pekkinen',
        player_role_in: '?',
        player_role_out: 'Linjapelaaja',
        player_info: 'https://www.pesistulokset.fi/pelaaja/7806',
      },
      {
        id: '11-11',
        image: '/images/placeholder.png',
        player_name: 'Jere Vikström',
        player_role_in: 'Vaihtaja',
        player_role_out: 'Sieppari',
        player_info: 'https://www.pesistulokset.fi/pelaaja/6201',
      },
      {
        id: '11-12',
        image: '/images/placeholder.png',
        player_name: 'Jussi Korhonen',
        player_role_in: 'Vaihtaja',
        player_role_out: 'Koppari',
        player_info: 'https://www.pesistulokset.fi/pelaaja/5173',
      },
      {
        id: '11-13',
        image: '/images/placeholder.png',
        player_name: 'Kalle Kuosmanen',
        player_role_in: 'Vaihtaja',
        player_role_out: 'Pesävahti',
        player_info: 'https://www.pesistulokset.fi/pelaaja/9182',
      },
      {
        id: '11-14',
        image: '/images/placeholder.png',
        player_name: 'Kasperi Vehkaoja',
        player_role_in: 'Vaihtaja',
        player_role_out: 'Pesävahti',
        player_info: 'https://www.pesistulokset.fi/pelaaja/10468',
      },
      {
        id: '11-15',
        image: '/images/placeholder.png',
        player_name: 'Miika Keski-Petäjä',
        player_role_in: 'Vaihtaja',
        player_role_out: 'Lukkari',
        player_info: 'https://www.pesistulokset.fi/pelaaja/7235',
      },
      {
        id: '11-16',
        image: '/images/placeholder.png',
        player_name: 'Roope Korhonen',
        player_role_in: 'Kotiuttaja',
        player_role_out: 'Jokeri',
        player_info: 'https://www.pesistulokset.fi/pelaaja/1456',
      },
      {
        id: '11-17',
        image: '/images/placeholder.png',
        player_name: 'Samuel Huotari',
        player_role_in: 'Kotiuttaja',
        player_role_out: 'Linjapelaaja',
        player_info: 'https://www.pesistulokset.fi/pelaaja/10559',
      },
      {
        id: '11-18',
        image: '/images/placeholder.png',
        player_name: 'Tommi Piirainen',
        player_role_in: 'Kotiuttaja',
        player_role_out: 'Jokeri',
        player_info: 'https://www.pesistulokset.fi/pelaaja/11552',
      },
      {
        id: '11-19',
        image: '/images/placeholder.png',
        player_name: 'Veeti Kokko',
        player_role_in: 'Vaihtaja',
        player_role_out: 'Sieppari',
        player_info: 'https://www.pesistulokset.fi/pelaaja/10087',
      },
      {
        id: '11-20',
        image: '/images/placeholder.png',
        player_name: 'Vertti Veittikoski',
        player_role_in: 'Jokeri',
        player_role_out: 'Jokeri',
        player_info: 'https://www.pesistulokset.fi/pelaaja/10950',
      },
      {
        id: '11-21',
        image: '/images/placeholder.png',
        player_name: 'Ville Veittikoski',
        player_role_in: 'Vaihtaja',
        player_role_out: 'Pesävahti',
        player_info: 'https://www.pesistulokset.fi/pelaaja/9071',
      },
    ],
    coaches: [
      {
        id: '11-1',
        image: '/images/placeholder.png',
        coach_name: 'Iiro Haimi',
        coach_role: '1. Pelinjohtaja',
      },
      {
        id: '11-2',
        image: '/images/placeholder.png',
        coach_name: 'Petteri Timonen',
        coach_role: '2. Pelinjohtaja',
      },
    ],
  },

  {
    id: '12',
    name: 'Vimpelin Veto',
    image: '/images/vimpelin_veto.png',
    description:
      'Vimpelin Veto on perustettu 27. toukokuuta vuonna 1934 ja toimii Vimpelissä, Etelä-Pohjanmaalla. Nykyisin seuran lajivalikoimana on pesäpallo, koripallo ja elektroninen urheilu. Vimpelin Vedon pesäpallojoukkueen kotikenttä on Saarikenttä. Vuonna 2010 Vimpelin Veto voitti finaaleissa Kouvolan Pallonlyöjät, ja toisessa loppuottelussa syntyi Saarikentällä pelattujen SM-sarjaotteluiden yleisöennätys 5 216 katsojaa. Joukkueen peliasun päävärit ovat valkoinen ja sininen.',
    achievements:
      'Vimpelin Vedon miesten pesäpallojoukkue on saavuttanut kultaa vuosina 1960, 1965, 2010, 2016, 2017 ja 2022. Hopealle se on sijoittunut vuosina 1959, 1961, 1962, 1966, 1975, 2011, 2012, 2013, 2014, 2015 ja 2023 sekä pronssille vuosina 1940, 1946, 1952, 1958, 1963, 1964, 1967, 1968, 2009, 2018, 2020 ja 2021.',
    arena: 'Saarikenttä',
    arena_image: '/images/saarikentta.jpg',
    players: [
      {
        id: '12-1',
        image: '/images/placeholder.png',
        player_name: 'Elmeri Anttila',
        player_role_in: 'Kotiuttaja',
        player_role_out: 'Koppari',
        player_info: 'https://www.pesistulokset.fi/pelaaja/8573',
      },
      {
        id: '12-2',
        image: '/images/placeholder.png',
        player_name: 'Juho Heikkala',
        player_role_in: 'Vaihtaja',
        player_role_out: 'Linjapelaaja',
        player_info: 'https://www.pesistulokset.fi/pelaaja/9754',
      },
      {
        id: '12-3',
        image: '/images/placeholder.png',
        player_name: 'Akseli Huusko',
        player_role_in: 'Vaihtaja',
        player_role_out: 'Linjapelaaja',
        player_info: 'https://www.pesistulokset.fi/pelaaja/12499',
      },
      {
        id: '12-4',
        image: '/images/placeholder.png',
        player_name: 'Mikko Kanala',
        player_role_in: 'Etenijä',
        player_role_out: 'Pesävahti',
        player_info: 'https://www.pesistulokset.fi/pelaaja/6131',
      },
      {
        id: '12-5',
        image: '/images/placeholder.png',
        player_name: 'Atte Kortehisto',
        player_role_in: 'Jokeri',
        player_role_out: 'Jokeri',
        player_info: 'https://www.pesistulokset.fi/pelaaja/10369',
      },
      {
        id: '12-6',
        image: '/images/placeholder.png',
        player_name: 'Veeti Kortehisto',
        player_role_in: 'Etenijä',
        player_role_out: 'Linjapelaaja',
        player_info: 'https://www.pesistulokset.fi/pelaaja/10438',
      },
      {
        id: '12-7',
        image: '/images/placeholder.png',
        player_name: 'Aleksi Lassila',
        player_role_in: 'Vaihtaja',
        player_role_out: 'Pesävahti',
        player_info: 'https://www.pesistulokset.fi/pelaaja/9940',
      },
      {
        id: '12-8',
        image: '/images/placeholder.png',
        player_name: 'Severi Lassila',
        player_role_in: 'Vaihtaja',
        player_role_out: 'Pesävahti',
        player_info: 'https://www.pesistulokset.fi/pelaaja/5985',
      },
      {
        id: '12-9',
        image: '/images/placeholder.png',
        player_name: 'Matias Rinta-aho',
        player_role_in: 'Kotiuttaja',
        player_role_out: 'Sieppari',
        player_info: 'https://www.pesistulokset.fi/pelaaja/5653',
      },
      {
        id: '12-10',
        image: '/images/placeholder.png',
        player_name: 'Jere Saukko',
        player_role_in: 'Etenijä',
        player_role_out: 'Jokeri',
        player_info: 'https://www.pesistulokset.fi/pelaaja/6311',
      },
      {
        id: '12-11',
        image: '/images/placeholder.png',
        player_name: 'Ville Soini',
        player_role_in: 'Vaihtaja',
        player_role_out: 'Lukkari',
        player_info: 'https://www.pesistulokset.fi/pelaaja/11676',
      },
      {
        id: '12-12',
        image: '/images/placeholder.png',
        player_name: 'Konsta Sova',
        player_role_in: 'Kotiuttaja',
        player_role_out: 'Pesävahti',
        player_info: 'https://www.pesistulokset.fi/pelaaja/11746',
      },
      {
        id: '12-13',
        image: '/images/placeholder.png',
        player_name: 'Eliel Koskela',
        player_role_in: 'Vaihtaja',
        player_role_out: 'Pesävahti',
        player_info: 'https://www.pesistulokset.fi/pelaaja/10249',
      },
      {
        id: '12-14',
        image: '/images/placeholder.png',
        player_name: 'Lauri Vihriälä',
        player_role_in: 'Vaihtaja',
        player_role_out: 'Pesävahti',
        player_info: 'https://www.pesistulokset.fi/pelaaja/10077',
      },
      {
        id: '12-15',
        image: '/images/placeholder.png',
        player_name: 'Mikko Vihriälä',
        player_role_in: 'Etenijä',
        player_role_out: 'Koppari',
        player_info: 'https://www.pesistulokset.fi/pelaaja/9082',
      },
      {
        id: '12-16',
        image: '/images/placeholder.png',
        player_name: 'Henri Puputti',
        player_role_in: 'Kotiuttaja',
        player_role_out: 'Koppari',
        player_info: 'https://www.pesistulokset.fi/pelaaja/1315',
      },
    ],
    coaches: [
      {
        id: '12-1',
        image: '/images/placeholder.png',
        coach_name: 'Mikko Parvi',
        coach_role: '1. Pelinjohtaja',
      },
      {
        id: '12-2',
        image: '/images/placeholder.png',
        coach_name: 'Pasi Tyynelä',
        coach_role: '2. Pelinjohtaja',
      },
    ],
  },
];

const resolvers = {
  Query: {
    teams: () => {
      return teams;
    },
    team: (root, { id }) => {
      return teams.find((team) => team.id === id);
    },
  },
};

const typeDefs = gql`
  type Team {
    id: ID!
    name: String
    image: ID
    description: String
    achievements: String
    arena: String
    arena_image: ID
    players: [Player]!
    coaches: [Coach]!
  }

  type Player {
    id: ID!
    image: ID
    player_name: String
    player_role_in: String
    player_role_out: String
    player_info: String
  }

  type Coach {
    id: ID!
    image: ID
    coach_name: String
    coach_role: String
  }

  type Query {
    teams: [Team]
    team(id: ID!): Team
  }
`;

async function startServer() {
  const app = express();

  const server = new ApolloServer({
    typeDefs,
    resolvers,
  });

  await server.start();

  app.use('/graphql', cors(), express.json(), expressMiddleware(server));

  // ====== SERVE VITE BUILD ======
  const distPath = path.join(__dirname, '../dist');

  app.use(express.static(distPath));

  app.get('*', (req, res) => {
    res.sendFile(path.join(distPath, 'index.html'));
  });
  // =================================

  const PORT = process.env.PORT || 4000;

  app.listen(PORT, () => {
    console.log(`🚀 Server running on port ${PORT}`);
  });
}

startServer();
